services:
  ecommerce-order-api:
    build:
      context: ./ecommerce-order-api
      dockerfile: Dockerfile
    container_name: ecommerce-order-api
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - minha-rede

  ecommerce-order-consumer:
    build: ./ecommerce-order-consumer
    container_name: ecommerce-order-consumer
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - minha-rede

  frontend:
    build: ecommerce-order-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - minha-rede

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - minha-rede

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - minha-rede


volumes:
  mongo_data:
  rabbitmq_data:

networks:
  minha-rede:
    driver: bridge