server:
  port: 8082

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        producerOrder-out-0:
          destination: order-created

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: orders_db

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "*"